### ISSUE TITLE
Separate start move message and reduce duplication

### ISSUE THREAD

**Issue by jxv** [rashadg1030/Reversi#2]
https://github.com/rashadg1030/Reversi/blob/d709aa7c1f7417ae4f1ef834e7ef4683c93f0d1a/src/Main.hs#L29-L32
Extract out into
```haskell
moveMessage :: Disc -> String
moveMessage disc  =  discName disc ++ "'s move. Enter location in the format (x,y). Ctrl + C to quit."

discName :: Disc -> String
discName White = "White"
discName Black = "Black"
```
And replace call with
```haskell
  putStrLn (moveMessage disc)
```

**Comment by jxv** [comment]
Also in general, be mindful when using `if` in place of pattern matching. (eg. `disc == Black`). `case` or pattern matching as arguments in functions is generally more maintainable. Non-exhaustive pattern matching errors will catch mistakes when refactoring and when adding another constructor.

**Comment by rashadg1030** [comment]
Okay, thank you! I fixed it.
